---

- name: Install dependencies
  apt: name=python-pycurl

- name: Add nginx repository
  apt_repository: repo=ppa:nginx/stable

- name: Install Dependencies
  apt: name={{item}}
  with_items: [nginx, python-passlib]
