---
- name: Provision nginx
  ec2:
    key_name: ansible
    ec2_region: '{{ aws.region }}'
    group: '{{ aws.environment }}-nginx'
    assign_public_ip: no
    vpc_subnet_id: '{{ item }}'
    instance_type: '{{ aws.ec2.nginx.instance_type }}'
    image: '{{ ubuntu_bionic_image_id }}'
    wait: true
    exact_count: '{{ aws.ec2.nginx.count_per_az }}'
    count_tag:
      Name: nginx
      environment: '{{ aws.environment }}'
      count_az: '{{ item }}'
    instance_tags:
      Name: nginx
      environment: '{{ aws.environment }}'
      count_az: '{{ item }}'
    monitoring: no
    user_data: '{{ cloud_config.aws.nginx }}'
  with_items: '{{ ec2_nginx_subnets }}'

- name: get facts on all nginx instances
  ec2_instance_facts:
    region: '{{ aws.region }}'
    filters:
      instance-state-name: running
      'tag:Name': nginx
      'tag:environment': '{{ aws.environment }}'
  register: nginx_gathered_facts

- name: provision nginx ELB external
  ec2_elb_lb:
    name: '{{ aws.ec2.nginx.elb.name }}'
    state: present
    region: '{{ aws.region }}'
    security_group_names: '{{ aws.environment }}-nginx'
    wait: no
    subnets: '{{ ec2_utility_subnets }}'
    purge_subnets: yes
    listeners:
      - protocol: tcp
        load_balancer_port: 443
        instance_protocol: tcp
        instance_port: 443
    health_check:
      ping_protocol: tcp
      ping_port: 443
      response_timeout: 5
      interval: 10
      unhealthy_threshold: 2
      healthy_threshold: 2
  register: nginx_elb

- name: Add nginx instances to ELB
  ec2_elb:
    region: '{{ aws.region }}'
    ec2_elbs: '{{ nginx_elb.elb.name }}'
    instance_id: '{{ item.instance_id }}'
    state: present
    wait: no
  with_items:
    - '{{ nginx_gathered_facts.instances }}'
  register: nginx_elb_add

- name: Setup route53 with ELB
  route53:
    command: create
    zone: '{{ aws.root_domain }}'
    record: 'nginx.{{ aws.root_domain }}'
    type: A
    ttl: 600
    value: '{{ nginx_elb.elb.dns_name }}'
    alias: true
    alias_hosted_zone_id: '{{ nginx_elb.elb.hosted_zone_id }}'
    overwrite: true
  when: '{{ nginx_elb_add.changed }}'
