---

- name: "Copy ssl key"
  copy:
    content: "{{ ssl_cert_account_key }}"
    dest: /etc/ssl/domain.key
    owner: root
    group: root
    mode: 0640
  notify: nginx restart

- name: "Copy ssl fullchain certificate"
  copy:
    content: "{{ ssl_cert_fullchain }}"
    dest:  /etc/ssl/domain.crt
    owner: root
    group: root
    mode: 0644
  notify: nginx restart

- name: "Add site config"
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/site.conf
    owner: root
    group: root
    mode: 0640
  notify: nginx reload
